all:
  children:
    # MySQL HA Cluster
    mysql:
      children:
        mysql_master:
          hosts:
            db-01:
              ansible_host: 192.168.100.135
              mysql_server_id: 1
              mysql_role: master
        mysql_slave:
          hosts:
            db-02:
              ansible_host: 192.168.100.136
              mysql_server_id: 2
              mysql_role: slave
              mysql_master_host: 192.168.100.135

    # Redis HA Cluster
    redis:
      children:
        redis_master:
          hosts:
            redis-01:
              ansible_host: 192.168.100.137
              redis_role: master
        redis_slave:
          hosts:
            redis-02:
              ansible_host: 192.168.100.138
              redis_role: slave
              redis_master_host: 192.168.100.137
        redis_sentinel:
          hosts:
            redis-03:
              ansible_host: 192.168.100.139

    # Kafka Cluster
    kafka:
      hosts:
        kafka-01:
          ansible_host: 192.168.100.140
          kafka_broker_id: 1
        kafka-02:
          ansible_host: 192.168.100.141
          kafka_broker_id: 2
        kafka-03:
          ansible_host: 192.168.100.142
          kafka_broker_id: 3

    # Zookeeper
    zookeeper:
      hosts:
        kafka-01:
          ansible_host: 192.168.100.140
          zk_id: 1

    # UI Tools Server - Docker containers
    ui_tools:
      hosts:
        ui-mo:
          ansible_host: 192.168.100.143

    # ProxySQL
    proxy:
      hosts:
        proxysql:
          ansible_host: 192.168.100.144

    # Backup Server
    backup:
      hosts:
        backup-01:
          ansible_host: 192.168.100.145

  vars:
    ansible_user: linhtc
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes
    ansible_become_method: sudo
